### ISSUE TITLE
Post Reply on a Comment(3)

### ISSUE THREAD

**Issue by songrenzhao** [jinchen1036/rdb-crud-microservice#102]
Technical Background:
- Currently we allow user to post comments freely, we have to allow users to interact as well. That is, we have to allow users to post reply on any comment

Acceptance Criteria:
- Create a new API **POST** `Post Reply on a Comment` with api `{{unifree}}/api/v1/post/postreply` such that accepts the following body
 ```
   {
      "commentID": required, int,
      "content": required, int,
   }
   ```
- Return body of the API - Success Example
```
{
    "status": "success",
    "data": [
        1
    ]
}
```

- Return body of the API - Failure Example

```
{
    "status": "error",
    "message": "Comment Not Found"
}
```

**Comment by JiejayLan** [comment]
If we delete a comment, do we need to delete all corresponding reply?

**Comment by jinchen1036** [comment]
Yes, since reply is a column in the comment table, so by delete the comment, its reply also get delete.

**Comment by jinchen1036** [comment]
Finished
