### ISSUE TITLE
Get Post by PostID - Fixed Return When PostID not found

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#72]
Technical background:
- Should return 404 when postID is not found for `GET` request `{unifree}/api/v1/user/getpostbyid` 
- Reference Issue #71

Acceptance Criteria:
- Create a `GET` request `{unifree}/api/v1/user/getpostbyid` 
   - Return error if PostID not exist 
- Modify the test cases

**Comment by songrenzhao** [comment]
Done
