### ISSUE TITLE
Fix Mapping between - Username and Posts

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#73]
Technical Background
- Current Logic: Retrieve username by posterID in the loop, long search time in DB 
- Potential Fix Logic
   1. Retrieve all userID and its associate username at once and store as dictionary in node
      - Pro: Much short search time in DB, not need to async in the loop
      - Con: Crash the CPU storage if a lot users store in the DB - not long term solution
   2. Add field in Post Table - Username
      - Pro: Retrieve username with the post
      - Con: Increase the unnecessary storage in DB
   3. Select Join
- Reference Issue: #70 

Acceptance Criteria
- Implement efficiency way to retrieve the username of each post

**Comment by JiejayLan** [comment]
But userID is a primary key, which is automatically indexed.I don't think the username match is very slow. What do you think?

**Comment by songrenzhao** [comment]
Rejected
