### ISSUE TITLE
View All Comments by Post ID (3)

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#77]
Technical background:
- User should be able to view all the comments by selected post
- Should have pagination 

Acceptance Criteria:
- Create a `Get` request `{url}/api/v1/post/viewcomments` such that it return with all comments 
  - The format of the return body is the following 
     ```
     {
        status: string ("success" or "error")
        data: {
                currentPage: int
                totalPages: int
                pageSize: int
                comments: [
                          {
                              username: string
                              commentID: int
                              commenterID: int
                              content: string
                              createdAt: timestamp
                              numReply: int
                          }
                        ...
                 ]
          }
     }
     ```
- Request header must contains a valid JWT token
- Require Query
    1. postID: int
- Optional Query
    1. currentPage: int 
    2. pageSize: int

**Comment by songrenzhao** [comment]
Done
