### ISSUE TITLE
Create Comment for Selected Post by User (2)

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#78]
Technical background:
- User should be able to create comment for the post

Acceptance Criteria:
- Create a `POST` request `{url}/api/v1/post/postcomment` 
  - The format of the request body is the following 
     ```
     {
        postID: int
        content: string
     }
     ```
- Request header must contains a valid JWT token
- Return Body - Return the create comment 

     ```
     {
        status: string ("success" or "error")
        data: 
         {
                  username: string
                  commentID: int
                  commenterID: int
                  content: string
                  createdAt: timestamp
                  numReply: int
          }
     }
     ```

**Comment by JiejayLan** [comment]
Be more specific, a successfully created comment request will also increase the numReply of the corresponding post entry by 1. Similar for the delete

**Comment by songrenzhao** [comment]
Done
