### ISSUE TITLE
Update Comment by CommentID (2)

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#79]
Technical background:
- User should be able to edit his/her comment 

Acceptance Criteria:
- Create a `PUT` request `{url}/api/v1/user/updatecomment` such that it update a corresponding comment.
  - The format of the request body is the following 
     ```
     {
        commentID: int
        content: string
     }
     ```
- Request header must contains a valid JWT token
- Return Body 
     ```
     {
        success: boolean
        comment: 
          {
              username: string
              commentID: int
              content: string
              createdAt: timestamp
              updatedAt: timestamp
              numReply: int
              canEdit: boolean
          }
     }
     ```

**Comment by JiejayLan** [comment]
In the return body, you may also want to return the update comment information, which can be used to  update the frontend

**Comment by jinchen1036** [comment]
Is it only need to return the update comment information, or all the comments. Since if just return the updated comment, might cause problem for the comment pagination.

**Comment by songrenzhao** [comment]
will not do
