### ISSUE TITLE
Add Number of Comment for Individual Post (3)

### ISSUE THREAD

**Issue by jinchen1036** [jinchen1036/rdb-crud-microservice#87]
Technical background:
- Add numComment for each post

Acceptance Criteria:
- Edit Post Table in Database - `numComment`
- For `Get` post request, should also return `numComment` in each post
- For `Put` update post request, should also update the `numComment` field
- For `Delete` post request, should also update the `numComment` field

**Comment by songrenzhao** [comment]
Won't do since pagination #68 already existed in each post's response.
