### ISSUE TITLE
User Profile Features

### ISSUE THREAD

**Issue by songrenzhao** [jinchen1036/rdb-crud-microservice#95]
Technical Background:
- As more users are posting their thoughts, it is becoming difficult to identify what school they are from
- Due to time restriction, we can only extract universities from emails. Like xxx@asdf.cuny.edu. We will extract CUNY out

Issues related:
#99 #98 #97 #96 

Acceptance Criteria:
- Should modify `Sign Up User Account` logic to accept school in database
- Should default `school` into their university
- Should rename `label` to `school` in the response of  `Get Posts` 
- Should rename `label` to  `school` in the response of  `Get Post by postID`
- Should rename `label` to  `school` in the response of  `Get Comments`

**Comment by JiejayLan** [comment]
I dont suggest to do that
-  if we extract the Abbreviation， we still don't know what school is that
-  different school email has different format

**Comment by JiejayLan** [comment]
We have too much things to do for next sprint, we need to narrow down our target and fix some bugs. 
- we still missing the post comment filter at home page

**Comment by jinchen1036** [comment]
Agree, we cannot just extract the part from the email to determine the university. Please see #86 as this ticket have created before for university match.

Questions: why need to return the school field from all get responses? Don't we restrict the user to view the post that belong to its school, or they can view everything?

Please consider the time and people who will work on the backend for this sprint,  do not think we can finish all the features wanted.

**Comment by songrenzhao** [comment]
All issues are completed, Done
